[phases.setup]
nixPkgs = ['nodejs_22', 'git', 'ffmpeg']

[phases.install]
cmds = [
  'npm ci --legacy-peer-deps --omit=optional --loglevel=error --ignore-scripts',
  'cd frontend && npm ci --legacy-peer-deps --omit=optional --loglevel=error --omit=dev',
  'cd backend && npm ci --legacy-peer-deps --omit=optional --loglevel=error --omit=dev'
]

[phases.build]
cmds = [
  'npm run build:frontend',
  'npm run build:backend'
]

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'
CI = 'false'
ESLINT_NO_DEV_ERRORS = 'true'
